version: 2
updates:
  - package-ecosystem: "npm" # or any other ecosystem like "bundler", "pip", etc.
    directory: "/" # location of the package manifests
    schedule:
      interval: "daily" # or "weekly", "monthly"
    target-branch: "dependabot-work" # specify the branch you want Dependabot to create PRs against
    commit-message:
      prefix: "chore(deps):" # prefix for the commit message
    commit-author:
      name: "dependabot[bot]"
