[build]
  base = "."
  publish = "packages/web-components/storybook-static"
  command = "npm run build.web-comps && cd packages/web-components && npm run build.storybook"

[build.environment]
  NODE_VERSION = "18"
