describe('Modal', () => {
    beforeEach(() => {
        cy.visitComponent('rux-modal')
    })
    it('renders', () => {
        cy.get('rux-modal').should('have.class', 'hydrated')
    })
    it('should close and open the modal', () => {
        cy.get('rux-modal').then(($modal) => {
            $modal[0].setAttribute('open', false)
        })
        cy.get('rux-modal').then(($modal) => {
            $modal[0].setAttribute('open', true)
        })
        cy.get('rux-modal').shadow().find('.rux-modal__wrapper').should('exist')
    })
    it('should not on off click if click-to-close if false', () => {
        cy.get('rux-modal')
            .shadow()
            .find('.rux-modal__wrapper')
            .click('topLeft')
        cy.get('rux-modal').shadow().find('.rux-modal__wrapper').should('exist')
    })
    it('should close on off click if click-to-close is true', () => {
        cy.get('rux-modal').then(($modal) => {
            $modal[0].setAttribute('click-to-close', true)
        })
        cy.get('rux-modal')
            .shadow()
            .find('.rux-modal__wrapper')
            .click('topLeft')
        cy.get('rux-modal')
            .shadow()
            .find('.rux-modal__wrapper')
            .should('not.exist')
    })
    it('should accept props and slots, but props will take priority', () => {
        cy.get('rux-modal').then(($modal) => {
            $modal[0].setAttribute('open', false)
        })
        cy.get('#open').click()
        cy.get('#test')
            .shadow()
            .find('.rux-modal__props-message')
            .should('exist')
        cy.get('#test').shadow().find('.rux-modal__content').should('not.exist')
    })
    it('should apply correct classes if using slots', () => {
        cy.get('rux-modal').then(($modal) => {
            $modal[0].setAttribute('open', false)
            $modal[1].setAttribute('open', false)
        })

        cy.get('#open-slots').click()
        cy.get('#test-slots')
            .shadow()
            .find('.rux-modal__content')
            .should('exist')
        cy.get('#test-slots')
            .shadow()
            .find('.rux-modal__titlebar')
            .should('exist')
        cy.get('#test-slots')
            .shadow()
            .find('.rux-modal__footer')
            .should('exist')

        cy.get('#test-slots')
            .shadow()
            .find('.rux-modal__props-message')
            .should('not.exist')
        cy.get('#test-slots')
            .shadow()
            .find('.rux-modal__props-message')
            .should('not.exist')
        cy.get('#test-slots')
            .shadow()
            .find('.rux-modal__props-message')
            .should('not.exist')
    })
})
